- deployment: deployWeb
  displayName: Deploy web pkg
  pool:
    vmImage: 'Ubuntu 16.04'
  environment: production    # create environment and/or record deployments
  strategy:                  # runOnce/blue green/rolling/canary, with lifecycle hooks viz, pre/post healthcheck, swap etc
    runOnce:                 # default strategy
      deploy:
        steps:       
        - script: echo deploy web pkg